/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_SERVER_URL: string
  readonly VITE_ELECTRIC_URL: string
  readonly VITE_ELECTRIC_SOURCE_SECRET: string
  readonly VITE_ELECTRIC_SOURCE_ID: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}