/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "RemixExample": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "remix": {
      "type": "sst.aws.Remix"
      "url": string
    }
  }
}
