/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Tanstack": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "TanstackBackend": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
