env:
  DOCKER_REPO: europe-docker.pkg.dev/vaxine/electric
  IMAGE_NAME: electric

agent:
  docker: true
  gcp: true

steps:
  - label: ":whale: Build & push the electric container"
    command:
      - export ELECTRIC_IMAGE_NAME="${DOCKER_REPO}/${IMAGE_NAME}"
      - export ELECTRIC_IMAGE_TAG=$(echo $BUILDKITE_COMMIT | head -c 7)
      - make docker-build-ci
      - docker tag "$${ELECTRIC_IMAGE_NAME}:$${ELECTRIC_IMAGE_TAG}" "$${ELECTRIC_IMAGE_NAME}:latest"
      - docker push "$${ELECTRIC_IMAGE_NAME}:latest"