env:
  DOCKERHUB_REPO: electricsql
  IMAGE_NAME: electric

agent:
  docker: true
  gcp: true

steps:
  - label: "🐤 Build & publish the canary image to Docker Hub"
    if: build.branch == "main"
    command:
      - git fetch --tags
      - export ELECTRIC_IMAGE_NAME="${DOCKER_REPO}/${IMAGE_NAME}"
      - cd ./packages/sync-service
      - export ELECTRIC_VERSION=$(git describe --abbrev=7 --tags --always --first-parent --match '@core/sync-service@*' | sed -En 's|^@core/sync-service@||p')
      - docker buildx build --platform linux/arm64/v8,linux/amd64 --push
        --build-arg ELECTRIC_VERSION=$${ELECTRIC_VERSION}
        -t $${ELECTRIC_IMAGE_NAME}:canary
  - wait
  - label: "🚀 Build & publish the release image to Docker Hub"
    if: build.tag =~ /@core\/sync-service@/
    command:
      - export ELECTRIC_IMAGE_NAME="${DOCKERHUB_REPO}/${IMAGE_NAME}"
      - cd ./packages/sync-service
      - export ELECTRIC_VERSION=$(jq '.version' -r package.json)
      - docker buildx build --platform linux/arm64/v8,linux/amd64 --push
        --build-arg ELECTRIC_VERSION=$${ELECTRIC_VERSION}
        -t $${ELECTRIC_IMAGE_NAME}:$${ELECTRIC_VERSION}
        -t $${ELECTRIC_IMAGE_NAME}:latest
        .
