# Run using `docker compose -f databases.yaml up`.
version: '3.7'

services:
  vaxine_1:
    extends:
      file: ../services_templates.yaml
      service: vaxine
    environment:
      NODE_NAME: "vaxine@vaxine_1"
    volumes:
      - ${VAXINE_VOLUME}/vaxine_1:/vaxine-data
    ports:
      - "8087:8087"
      - "8088:8088"

  vaxine_2:
    extends:
      file: ../services_templates.yaml
      service: vaxine
    environment:
      NODE_NAME: "vaxine@vaxine_2"
    volumes:
      - ${VAXINE_VOLUME}/vaxine_2:/vaxine-data
    ports:
      - "8089:8087"
      - "8090:8088"

  vaxine_3:
    extends:
      file: ../services_templates.yaml
      service: vaxine
    environment:
      NODE_NAME: "vaxine@vaxine_3"
    volumes:
      - ${VAXINE_VOLUME}/vaxine_3:/vaxine-data
    ports:
      - "8091:8087"
      - "8092:8088"

  electric_1:
    extends:
      file: ../services_templates.yaml
      service: electric
    environment:
      VAXINE_HOST: vaxine_1
      ELECTRIC_HOST: electric_1
      CONNECTORS: >-
        pg_1=postgresql://postgres:password@pg_1:5432/electric;
      ELECTRIC_INSTANCE_ID: instance-a.region-1.test.electric-db
      ELECTRIC_REGIONAL_ID: region-1.test.electric-db
    depends_on:
      - pg_1
      - vaxine_1

  electric_2:
    extends:
      file: ../services_templates.yaml
      service: electric
    environment:
      VAXINE_HOST: vaxine_2
      ELECTRIC_HOST: electric_2
      CONNECTORS: >-
        pg_2=postgresql://postgres:password@pg_2:5432/electric;
      ELECTRIC_INSTANCE_ID: instance-a.region-2.test.electric-db
      ELECTRIC_REGIONAL_ID: region-2.test.electric-db
    depends_on:
      - pg_2
      - vaxine_2

  electric_3:
    extends:
      file: ../services_templates.yaml
      service: electric
    environment:
      VAXINE_HOST: vaxine_3
      ELECTRIC_HOST: electric_3
      CONNECTORS: >-
        pg_3=postgresql://postgres:password@pg_3:5432/electric;
      ELECTRIC_INSTANCE_ID: instance-a.region-3.test.electric-db
      ELECTRIC_REGIONAL_ID: region-3.test.electric-db
    depends_on:
      - pg_3
      - vaxine_3

  sysbench:
    extends:
      file: ../services_templates.yaml
      service: sysbench

  pg_1:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    ports:
      - "54321:5432"

  pg_2:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    ports:
      - "54322:5432"

  pg_3:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    ports:
      - "54323:5432"

  ctrl:
    environment:
      GODEBUG: netdns=go
    image: peterzel/antidote-connect
