import { useState } from 'react'
import { ColumnDef, TableView } from './components/TableView'
import { PaginationState, SortingState, useTableData } from './use_table_data'

export const TableDataViewer = ({
  columns,
  whereClause,
}: {
  columns: ColumnDef[]
  whereClause: string
}) => {
  // Keep pagination state to only load necessary data
  const [pagination, setPagination] = useState<PaginationState>({
    pageIndex: 0,
    pageSize: 5,
  })

  // Keep an order by clause generated by the sorting of columns
  const [sorting, setSorting] = useState<SortingState[]>([])

  const { orders, totalNumberOfOrders } = useTableData({
    sorting,
    pagination,
    whereClause,
  })

  return (
    <TableView
      columns={columns}
      rows={orders}
      totalNumberOfRows={totalNumberOfOrders}
      pagination={pagination}
      onPaginationChange={setPagination}
      sorting={sorting}
      onSortingChange={setSorting}
    />
  )
}
