import Config

# Configure your database - using standard PostgreSQL setup
config :todo_phoenix, TodoPhoenix.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "todo_phoenix_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Phoenix.Sync configuration for embedded Electric
config :phoenix_sync,
  mode: :embedded,
  repo: TodoPhoenix.Repo

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :todo_phoenix, TodoPhoenixWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "jAle4rkA0/HuI5ZGmWHOjkYqVt3YY4jcSmW8zW2A8Oqlhf8W0KNMeaTwmMYHKSKp",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:todo_phoenix, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:todo_phoenix, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :todo_phoenix, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
