/*
  Autogenerated ElectricSQL config file. Don't edit this
  file directly. Instead, use the `electric` CLI tool
  to manage your config and migrations.

  See https://electric-sql.com/docs for more information.
*/

export default {
  app: 'tarragon-envy-5432',
  build: 'local',
  env: 'default',
  migrations: [],
}
