export const VERSION = `0.1.0`
export * from './types'
export { createMcpTools } from './tools'
export type { McpToolsHandle } from './tools'
export { createRegistry } from './registry'
export type { Registry, RegistryOpts, ServerEntry } from './registry'
export { createFileVault } from './vault/file-vault'
export type { KeyVault } from './vault/types'
export type { FileVaultOptions } from './vault/file-vault'
export { loadConfig, parseConfig } from './config/loader'
export type { McpConfig } from './config/loader'
export { watchConfig } from './config/watcher'
export { defaultTransportFactory } from './transports/factory'
export { TimeoutError, withTimeout } from './transports/timeout'
export { bridgeMcpTool } from './bridge/tool-bridge'
export type { BridgedTool, BridgeOpts } from './bridge/tool-bridge'
