name: Test Example
description: "Test a deployed example"

inputs:
  example_url:
    description: "URL of the deployed example"
    required: true
  test_folder:
    description: "Folder containing the tests to run"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: inputs.example_url != ''
      uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      if: inputs.example_url != ''
    - uses: actions/setup-node@v4
      if: inputs.example_url != ''
      with:
        node-version-file: ".tool-versions"
        cache: pnpm
    - shell: bash
      if: inputs.example_url != ''
      run: pnpm install --frozen-lockfile
    - name: Run browser tests
      if: inputs.example_url != ''
      working-directory: examples/${{ inputs.test_folder }}
      shell: bash
      run: pnpm test:browser
      env:
        BASE_URL: ${{ inputs.example_url }}
