import { execSync } from 'child_process'
import { randomBytes } from 'crypto'
import { writeFileSync, readFileSync, existsSync } from 'fs'
import { join } from 'path'

export const TEMPLATE_REPO_PATH = `electric-sql/electric/tree/main/examples/tanstack-db-web-starter`

/**
 * Connection settings for the Postgres and Electric services defined in the
 * starter's `docker-compose.yaml`.
 */
export const LOCAL_DATABASE_URL = `postgresql://postgres:password@localhost:54321/electric`
export const LOCAL_ELECTRIC_URL = `http://localhost:30000`

/**
 * Generates a cryptographically secure random string for use as a secret
 * @param length - The length of the secret in bytes (will be hex encoded, so output is 2x length)
 * @returns A random hex string
 */
function generateSecret(length: number = 32): string {
  return randomBytes(length).toString(`hex`)
}

export async function setupTemplate(appName: string): Promise<void> {
  const appPath = appName === `.` ? process.cwd() : join(process.cwd(), appName)

  try {
    // Step 1: Pull the starter template using gitpick (skip for current directory)
    if (appName !== `.`) {
      console.log(`Pulling template...`)
      execSync(`npx gitpick ${TEMPLATE_REPO_PATH} ${appName}`, {
        stdio: `inherit`,
      })
    }

    // Step 2: Generate .env file pointing at the local Docker services
    console.log(`Configuring environment...`)
    const betterAuthSecret = generateSecret(32)
    const envContent = `# Electric SQL Configuration
# Generated by @electric-sql/start
# DO NOT COMMIT THIS FILE

# Database (Postgres from docker-compose.yaml)
DATABASE_URL=${LOCAL_DATABASE_URL}

# Electric (sync service from docker-compose.yaml)
ELECTRIC_URL=${LOCAL_ELECTRIC_URL}

# Authentication
BETTER_AUTH_SECRET=${betterAuthSecret}
`

    writeFileSync(join(appPath, `.env`), envContent)

    // Step 3: Ensure .gitignore includes .env
    const gitignorePath = join(appPath, `.gitignore`)
    let gitignoreContent = ``

    if (existsSync(gitignorePath)) {
      gitignoreContent = readFileSync(gitignorePath, `utf8`)
    }

    if (!gitignoreContent.includes(`.env`)) {
      console.log(`Updating .gitignore...`)
      gitignoreContent += `\n# Environment variables\n.env\n.env.local\n.env.*.local\n`
      writeFileSync(gitignorePath, gitignoreContent)
    }

    console.log(`Template setup complete`)
  } catch (error) {
    throw new Error(
      `Template setup failed: ${error instanceof Error ? error.message : error}`
    )
  }
}
