import { execSync } from 'child_process'
import { randomBytes } from 'crypto'
import { writeFileSync, readFileSync, existsSync } from 'fs'
import { join } from 'path'
import {
  ElectricCredentials,
  getElectricUrl,
  getElectricDashboardUrl,
} from './electric-api'

interface SetupCredentials extends ElectricCredentials {
  claimId?: string
}

/**
 * Generates a cryptographically secure random string for use as a secret
 * @param length - The length of the secret in bytes (will be hex encoded, so output is 2x length)
 * @returns A random hex string
 */
function generateSecret(length: number = 32): string {
  return randomBytes(length).toString(`hex`)
}

export async function setupTemplate(
  appName: string,
  credentials: SetupCredentials
): Promise<void> {
  const appPath = appName === `.` ? process.cwd() : join(process.cwd(), appName)

  try {
    // Step 1: Pull TanStack Start template using gitpick (skip for current directory)
    if (appName !== `.`) {
      console.log(`Pulling template...`)
      execSync(
        `npx gitpick electric-sql/electric/tree/main/examples/tanstack-db-web-starter ${appName}`,
        { stdio: `inherit` }
      )
    }

    // Step 2: Generate .env file with credentials
    console.log(`Configuring environment...`)
    const betterAuthSecret = generateSecret(32)
    const electricUrl = getElectricUrl()
    const envContent = `# Electric SQL Configuration
# Generated by @electric-sql/start
# DO NOT COMMIT THIS FILE

# Database
DATABASE_URL=${credentials.DATABASE_URL}

# Electric Cloud
ELECTRIC_URL=${electricUrl}
ELECTRIC_SOURCE_ID=${credentials.source_id}
ELECTRIC_SECRET=${credentials.secret}

# Authentication
BETTER_AUTH_SECRET=${betterAuthSecret}
`

    writeFileSync(join(appPath, `.env`), envContent)

    // Step 3: Ensure .gitignore includes .env
    console.log(`Updating .gitignore...`)
    const gitignorePath = join(appPath, `.gitignore`)
    let gitignoreContent = ``

    if (existsSync(gitignorePath)) {
      gitignoreContent = readFileSync(gitignorePath, `utf8`)
    }

    if (!gitignoreContent.includes(`.env`)) {
      gitignoreContent += `\n# Environment variables\n.env\n.env.local\n.env.*.local\n`
      writeFileSync(gitignorePath, gitignoreContent)
    }

    console.log(`Adding Electric commands...`)
    const packageJsonPath = join(appPath, `package.json`)

    if (existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(readFileSync(packageJsonPath, `utf8`))

      // Add/update scripts for cloud mode and Electric commands
      const scripts: Record<string, string> = {
        ...packageJson.scripts,
        'deploy:netlify': `NODE_ENV=production NITRO_PRESET=netlify pnpm build && NODE_ENV=production npx netlify deploy --no-build --prod --dir=dist --functions=.netlify/functions-internal && npx netlify env:import .env`,
      }

      // Only add claim script if claimId is present (i.e., resources were provisioned)
      if (credentials.claimId) {
        scripts.claim = `npx open-cli "${getElectricDashboardUrl()}/claim?uuid=${credentials.claimId}"`
      }

      packageJson.scripts = scripts

      writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2))
    }

    console.log(`Template setup complete`)
  } catch (error) {
    throw new Error(
      `Template setup failed: ${error instanceof Error ? error.message : error}`
    )
  }
}
