import { execSync } from 'child_process'
import { randomBytes } from 'crypto'
import { writeFileSync, readFileSync, existsSync } from 'fs'
import { join } from 'path'
import {
  ElectricCredentials,
  DEFAULT_ELECTRIC_API_BASE,
  getElectricUrl,
} from './electric-api'

/**
 * Generates a cryptographically secure random string for use as a secret
 * @param length - The length of the secret in bytes (will be hex encoded, so output is 2x length)
 * @returns A random hex string
 */
function generateSecret(length: number = 32): string {
  return randomBytes(length).toString(`hex`)
}

export async function setupTemplate(
  appName: string,
  credentials: ElectricCredentials
): Promise<void> {
  const appPath = join(process.cwd(), appName)

  try {
    // Step 1: Pull TanStack Start template using gitpick
    console.log(`Pulling template...`)
    execSync(
      `npx gitpick electric-sql/electric/tree/main/examples/tanstack-db-web-starter ${appName}`,
      { stdio: `inherit` }
    )

    // Step 2: Generate .env file with credentials
    console.log(`Configuring environment...`)
    const betterAuthSecret = generateSecret(32)
    const electricUrl = getElectricUrl()
    const envContent = `# Electric SQL Configuration
# Generated by @electric-sql/start
# DO NOT COMMIT THIS FILE

# Database
DATABASE_URL=${credentials.DATABASE_URL}

# Electric Cloud
ELECTRIC_URL=${electricUrl}
ELECTRIC_SOURCE_ID=${credentials.source_id}
ELECTRIC_SECRET=${credentials.secret}

# Authentication
BETTER_AUTH_SECRET=${betterAuthSecret}
`

    writeFileSync(join(appPath, `.env`), envContent)

    // Step 3: Ensure .gitignore includes .env
    console.log(`Updating .gitignore...`)
    const gitignorePath = join(appPath, `.gitignore`)
    let gitignoreContent = ``

    if (existsSync(gitignorePath)) {
      gitignoreContent = readFileSync(gitignorePath, `utf8`)
    }

    if (!gitignoreContent.includes(`.env`)) {
      gitignoreContent += `\n# Environment variables\n.env\n.env.local\n.env.*.local\n`
      writeFileSync(gitignorePath, gitignoreContent)
    }

    // Step 4: Copy shared tsconfig.json if it doesn't exist
    const tsconfigPath = join(appPath, `tsconfig.json`)
    if (!existsSync(tsconfigPath)) {
      console.log(`Setting up TypeScript configuration...`)
      // Use a basic tsconfig.json template instead of copying from parent
      const tsconfigContent = JSON.stringify(
        {
          compilerOptions: {
            target: `es2020`,
            module: `commonjs`,
            moduleResolution: `node`,
            strict: true,
            esModuleInterop: true,
            allowSyntheticDefaultImports: true,
            skipLibCheck: true,
            types: [`node`],
          },
          include: [`src/**/*`],
          exclude: [`node_modules`, `dist`],
        },
        null,
        2
      )
      writeFileSync(tsconfigPath, tsconfigContent)
    }

    // Step 5: Extend package.json with additional scripts
    console.log(`Adding Electric commands...`)
    const packageJsonPath = join(appPath, `package.json`)

    if (existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(readFileSync(packageJsonPath, `utf8`))

      // Add/update scripts for cloud mode and Electric commands
      packageJson.scripts = {
        ...packageJson.scripts,
        // Dev mode scripts - cloud mode is default for `npx @electric-sql/start` apps
        dev: `pnpm dev:cloud`,
        'dev:cloud': `vite dev`,
        'dev:docker': `docker compose up -d && vite dev`,
        // Backend management for docker mode
        'backend:up': `docker compose up -d`,
        'backend:down': `docker compose down`,
        'backend:clear': `docker compose down -v`,
        // Electric-specific commands
        psql: `node -e "require('dotenv').config();require('child_process').execSync('psql \\\"'+process.env.DATABASE_URL+'\\\"',{stdio:'inherit'})"`,
        claim: `node -e "require(\\"./electric-commands\\").claim()"`,
        deploy: `NITRO_PRESET=netlify pnpm build && netlify deploy --prod --dir=dist --functions=.netlify/functions-internal`,
      }

      writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2))
    }

    // Step 6: Create electric-commands.js helper file
    console.log(`Setting up command helpers...`)
    const electricCommandsContent = `// Using native fetch (Node.js 18+)

const DEFAULT_ELECTRIC_API_BASE = '${DEFAULT_ELECTRIC_API_BASE}';

function getElectricApiBase() {
  return process.env.ELECTRIC_API_BASE_URL || DEFAULT_ELECTRIC_API_BASE;
}

async function claim() {
  const { ELECTRIC_SOURCE_ID, ELECTRIC_SECRET } = process.env;

  if (!ELECTRIC_SOURCE_ID || !ELECTRIC_SECRET) {
    console.error('Missing ELECTRIC_SOURCE_ID or ELECTRIC_SECRET environment variables');
    console.error('Make sure .env file exists and contains Electric credentials');
    process.exit(1);
  }

  try {
    const response = await fetch(\`\${getElectricApiBase()}/v1/claim\`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': \`Bearer \${ELECTRIC_SECRET}\`,
        'User-Agent': '@electric-sql/start'
      },
      body: JSON.stringify({
        source_id: ELECTRIC_SOURCE_ID
      })
    });

    if (!response.ok) {
      throw new Error(\`Electric API error: \${response.status} \${response.statusText}\`);
    }

    const result = await response.json();

    console.log('Resource claim initiated');
    console.log('');
    console.log('Open this URL in your browser to complete the claiming process:');
    console.log(result.claimUrl);
    console.log('');
    console.log('This will:');
    console.log('- Link Electric Cloud account');
    console.log('- Link Neon database account');
    console.log('- Transfer temporary resources');

  } catch (error) {
    console.error('Failed to initiate resource claim:', error.message);
    process.exit(1);
  }
}

module.exports = { claim };
`

    writeFileSync(
      join(appPath, `electric-commands.js`),
      electricCommandsContent
    )

    console.log(`Template setup complete`)
  } catch (error) {
    throw new Error(
      `Template setup failed: ${error instanceof Error ? error.message : error}`
    )
  }
}
