/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: `quickstart-example`,
      removal: input?.stage === `production` ? `retain` : `remove`,
      protect: [`production`].includes(input?.stage),
      home: `aws`,
      providers: {
        cloudflare: `5.42.0`,
        aws: {
          version: `6.66.2`,
          profile: process.env.CI ? undefined : `marketing`,
        },
      },
    }
  },
  async run() {
    // Validate required environment variables
    if (!process.env.ELECTRIC_API) {
      throw new Error(`ELECTRIC_API environment variable is required`)
    }
    if (!process.env.BETTER_AUTH_SECRET) {
      throw new Error(`BETTER_AUTH_SECRET environment variable is required`)
    }
    if (
      !process.env.QUICKSTART_DATABASE_URI ||
      !process.env.QUICKSTART_POOLED_DATABASE_URI ||
      !process.env.QUICKSTART_SOURCE_ID ||
      !process.env.QUICKSTART_SOURCE_SECRET
    ) {
      throw new Error(
        `QUICKSTART_DATABASE_URI, QUICKSTART_POOLED_DATABASE_URI, ` +
          `QUICKSTART_SOURCE_ID, and QUICKSTART_SOURCE_SECRET are required`
      )
    }

    // Apply migrations (idempotent)
    await applyDrizzleMigrations(process.env.QUICKSTART_DATABASE_URI)

    const website = new sst.aws.TanStackStart(`quickstart-website`, {
      environment: {
        // Database
        DATABASE_URL: process.env.QUICKSTART_POOLED_DATABASE_URI,

        // Electric
        ELECTRIC_URL: process.env.ELECTRIC_API,
        ELECTRIC_SOURCE_ID: process.env.QUICKSTART_SOURCE_ID,
        ELECTRIC_SECRET: process.env.QUICKSTART_SOURCE_SECRET,

        // Better Auth
        BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
        BETTER_AUTH_URL: `https://quickstart.examples.electric-sql.com`,
      },
      domain: {
        name: `quickstart.examples.electric-sql.com`,
        dns: sst.cloudflare.dns(),
      },
    })

    return {
      website: website.url,
    }
  },
})

/**
 * Apply migrations using Drizzle Kit.
 * Migrations are in src/db/out/ (generated by drizzle-kit generate).
 */
async function applyDrizzleMigrations(dbUri: string) {
  const { execSync } = await import(`node:child_process`)
  console.log(`[quickstart] Applying Drizzle migrations`)
  execSync(`pnpm drizzle-kit migrate`, {
    env: {
      ...process.env,
      DATABASE_URL: dbUri,
    },
  })
}
