# Run using `docker-compose -f databases.yaml up`.
version: '3.1'

services:
  vaxine_1:
    extends:
      file: ../services_templates.yaml
      service: vaxine
    environment:
      UID: ${UID}
      GID: ${GID}
    volumes:
      - ${VAXINE_VOLUME}/vaxine_1:/vaxine-data
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    ports:
      - "8087:8087"
      - "8088:8088"

  electric_1:
    extends:
      file: ../services_templates.yaml
      service: electric
    volumes:
      - ./electric.exs:/app/releases/0.1.0/runtime.exs:ro
    depends_on:
      - pg_1
      - pg_2
      - vaxine_1

  electric_2:
    extends:
      file: ../services_templates.yaml
      service: electric
    volumes:
      - ./electric_b.exs:/app/releases/0.1.0/runtime.exs:ro
    depends_on:
      - pg_3
      - vaxine_1

  pg_1:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    ports:
      - "54321:5432"

  pg_2:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    ports:
      - "54322:5432"

  pg_3:
    extends:
      file: ../services_templates.yaml
      service: postgresql
    ports:
      - "54323:5432"
