# This compose file is used by the CLI `start` command to run the sync service and, optionally,
# a Postgres database inside Docker containers.
#
# When a user wants to start only the sync service by executing `electric-sql start`, the CLI
# will execute `docker compose up ... electric`, omitting the "postgres" service, so only the
# "electric" service will be running.
#
# When `electric-sql start --with-postgres` is invoked, the CLI will execute `docker compose up
# ... postgres electric`. In this case, the sync service may spend some time in a reconnection loop
# until the Postgres database is ready to accept connections. This is a normal mode of operation.

configs:
  postgres_config:
    file: './postgres.conf'

volumes:
  pg_data:

networks:
  # An IPv6-enabled network is necessary for the sync service to connect to
  # databases that are only reachable at IPv6 addresses. IPv4 can also be used as usual with
  # this network.
  ip6net:
    enable_ipv6: true
    # These two options provide an escape hatch that allows users to define their own Docker
    # network using `docker network create` and make the services defined in this compose file
    # use that.
    external: '${DOCKER_NETWORK_USE_EXTERNAL:-false}'
    name: '${DOCKER_NETWORK_NAME-}'
    ipam:
      config:
        # Subnet definition isn't required if the Docker daemon has a default address pool for
        # IPv6 addresses configured. However, since that's not the case for Docker
        # out-of-the-box and since we want to free our users from additional manual
        # configuration when possible, we include a default subnet definition here that should
        # work with any Docker daemon configuration.
        #
        # The fd00:: prefix is part of the address space reserved for Unique Local Addresses,
        # i.e. private networks. This is analogous to 192.168.x.x in the IPv4 land.
        #
        # There is a possibility that this subnet overlaps with another network configured
        # separately for the same Docker daemon. That situation would result in `docker compose
        # up` failing with the error message
        #
        #     Error response from daemon: Pool overlaps with other one on this address space
        #
        # Users can specify a different subnet via the DOCKER_NETWORK_SUBNET variable to
        # address such conflicts.
        #
        # The default subnet here has 2 randomly generated bytes in the 2nd and the 6th groups,
        # it can accommodate 4 addresses which is small enough to further reduce any chance of conflicts.
        - subnet: '${DOCKER_NETWORK_SUBNET:-fd00:56f0::4acd:f0fc/126}'

services:
  postgres:
    profiles: ['with-postgres']
    image: '${POSTGRESQL_IMAGE:-postgres:14-alpine}'
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-electric}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-db_password}
    command:
      - -c
      - config_file=/etc/postgresql.conf
      - -p
      - ${DATABASE_PORT:-5432}
    configs:
      - source: postgres_config
        target: /etc/postgresql.conf
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DATABASE_USER:-postgres} -p ${DATABASE_PORT:-5432}',
        ]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ip6net

  electric:
    image: '${ELECTRIC_IMAGE:-electricsql/electric:latest}'
    init: true
    stop_signal: SIGINT # use SIGINT as the more speedy alternative to SIGTERM
    ports:
      - ${HTTP_PORT:-5133}:${HTTP_PORT:-5133}
      - ${PG_PROXY_PORT_PARSED:-65432}:${PG_PROXY_PORT_PARSED:-65432}
    environment:
      DATABASE_REQUIRE_SSL: ${DATABASE_REQUIRE_SSL:-}
      DATABASE_URL: ${DATABASE_URL:-}
      DATABASE_USE_IPV6: ${DATABASE_USE_IPV6:-}
      ELECTRIC_USE_IPV6: ${ELECTRIC_USE_IPV6:-}
      HTTP_PORT: ${HTTP_PORT:-5133}
      ELECTRIC_WRITE_TO_PG_MODE: ${ELECTRIC_WRITE_TO_PG_MODE:-}
      LOGICAL_PUBLISHER_HOST: ${LOGICAL_PUBLISHER_HOST:-}
      LOGICAL_PUBLISHER_PORT: ${LOGICAL_PUBLISHER_PORT:-5433}
      PG_PROXY_PASSWORD: ${PG_PROXY_PASSWORD:-proxy_password}
      PG_PROXY_PORT: ${PG_PROXY_PORT:-65432}
      AUTH_MODE: ${AUTH_MODE:-insecure}
      AUTH_JWT_ALG: ${AUTH_JWT_ALG:-}
      AUTH_JWT_AUD: ${AUTH_JWT_AUD:-}
      AUTH_JWT_ISS: ${AUTH_JWT_ISS:-}
      AUTH_JWT_KEY: ${AUTH_JWT_KEY:-}
      AUTH_JWT_NAMESPACE: ${AUTH_JWT_NAMESPACE:-}
      ELECTRIC_FEATURES: ${ELECTRIC_FEATURES:-}
    networks:
      # Despite the name, assigning this network to the sync service does not preclude the use
      # of IPv4.
      - ip6net
