/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import 'sst'
export {}
declare module 'sst' {
  export interface Resource {
    'write-patterns-production-vpc': {
      type: 'sst.aws.Vpc'
    }
    'write-patterns-service-production': {
      service: string
      type: 'sst.aws.Service'
      url: string
    }
    'write-patterns-website': {
      type: 'sst.aws.StaticSite'
      url: string
    }
  }
}
