# SubqueryIndex memory snapshot.
#
# Run from packages/sync-service:
#
#     mix run --no-start scripts/subquery_logical_time_memory.exs
#
# `--no-start` skips booting the sync-service application; this script only
# uses the SubqueryIndex / MultiTimeView modules and a small simulated
# consumer-side state, all in-process.
#
# Reproduces the "Logical" columns of the memory table in
# docs/rfcs/subquery-index.md (§Memory Savings Prototype). The corresponding
# "current model" numbers in that table were generated by a separate
# prototype that simulated the pre-RFC per-shape MapSet implementation; we
# don't reproduce them here because the old model code has been removed
# from this branch.
#
# Measured per scenario:
#   * ETS:        SubqueryIndex bag table + MultiTimeView set table.
#   * Consumers:  the compact `%{subquery_ref => %{subquery_id, time}}` map
#                 each shape holds, plus any in-flight ActiveMove structs.
#   * Total:      ETS + Consumers.

alias Electric.Replication.Eval.Parser.{Func, Ref}
alias Electric.Shapes.Consumer.Subqueries.ActiveMove
alias Electric.Shapes.DnfPlan
alias Electric.Shapes.Filter
alias Electric.Shapes.Filter.Indexes.SubqueryIndex
alias Electric.Shapes.Filter.Indexes.SubqueryIndex.MultiTimeView
alias Electric.Shapes.Filter.WhereCondition

defmodule MemBench do
  @field "par_id"
  @subquery_ref ["$sublink", "0"]
  @wordsize :erlang.system_info(:wordsize)

  def make_plan(polarity \\ :positive) do
    testexpr = %Ref{path: [@field], type: :int8}
    ref = %Ref{path: @subquery_ref, type: {:array, :int8}}

    ast = %Func{
      name: "sublink_membership_check",
      args: [testexpr, ref],
      type: :bool
    }

    %DnfPlan{
      disjuncts: [],
      disjuncts_positions: [],
      position_count: 1,
      positions: %{
        0 => %{
          ast: ast,
          sql: "fake",
          is_subquery: true,
          negated: polarity == :negated,
          dependency_index: 0,
          subquery_ref: @subquery_ref,
          tag_columns: [@field]
        }
      },
      dependency_positions: %{0 => [0]},
      dependency_disjuncts: %{},
      dependency_polarities: %{0 => polarity}
    }
  end

  def opt do
    %{
      operation: "subquery",
      field: @field,
      testexpr: %Ref{path: [@field], type: :int8},
      subquery_ref: @subquery_ref,
      dep_index: 0,
      polarity: :positive,
      and_where: nil
    }
  end

  # Build a Filter with one subquery containing `value_count` base values,
  # `shape_count` shapes attached, all at time 0.
  def build_steady(shape_count, value_count) do
    filter = Filter.new()
    condition_id = make_ref()
    WhereCondition.init(filter, condition_id)
    index = filter.subquery_index
    dep = "dep_a"

    values = for v <- 1..value_count, do: v
    MultiTimeView.init_subquery(index.multi_time_view, dep, values)
    MultiTimeView.mark_ready(index.multi_time_view, dep)

    shape_ids =
      for i <- 1..shape_count do
        shape_id = "shape_#{i}"
        SubqueryIndex.register_shape(index, shape_id, make_plan(), [dep])
        SubqueryIndex.add_shape(filter, condition_id, shape_id, opt(), [])
        SubqueryIndex.mark_ready(index, shape_id)
        shape_id
      end

    consumer_states =
      for _ <- 1..shape_count, do: %{@subquery_ref => %{subquery_id: dep, time: 0}}

    %{filter: filter, dep: dep, shape_ids: shape_ids, consumer_states: consumer_states}
  end

  # Layer on `added_count` values across `time_steps` logical timesteps.
  # Each added value enters the MTV via mark_in at a logical time spread
  # uniformly across [1, time_steps]. Old times are retained because not
  # every consumer has advanced past them.
  def apply_advanced(state, added_count, time_steps) do
    %{filter: filter, dep: dep, shape_ids: shape_ids, consumer_states: consumer_states} =
      state

    index = filter.subquery_index
    mtv = index.multi_time_view

    base_value = 1_000_000

    for i <- 1..added_count do
      value = base_value + i
      # Spread the adds across the available time steps. Floor division so
      # each step gets a roughly equal slice.
      step = div((i - 1) * time_steps, added_count) + 1
      MultiTimeView.mark_in(mtv, dep, value, step)
      SubqueryIndex.add_positive_route(index, dep, value)
    end

    # Advance each consumer to a logical time spread across [0, time_steps].
    # This leaves a non-trivial retention window so histories accumulate.
    consumer_states =
      consumer_states
      |> Enum.with_index(0)
      |> Enum.map(fn {state, idx} ->
        target = div(idx * time_steps, length(shape_ids))
        Map.update!(state, @subquery_ref, &%{&1 | time: target})
      end)

    %{state | consumer_states: consumer_states}
  end

  # Add `move_count` in-flight ActiveMove structs. `total_moved_values` is
  # split evenly across the moves.
  def apply_active_moves(state, move_count, total_moved_values) do
    dep = state.dep
    values_per_move = max(1, div(total_moved_values, max(move_count, 1)))

    active_moves =
      for i <- 1..move_count do
        from_t = i
        to_t = i + 1

        move_in_values =
          for j <- 1..values_per_move do
            value = 2_000_000 + i * values_per_move + j
            {value, "v#{value}"}
          end

        %ActiveMove{
          subquery_id: dep,
          dep_index: 0,
          subquery_ref: @subquery_ref,
          from_time: from_t,
          to_time: to_t,
          move_in_values: move_in_values,
          move_out_values: [],
          txids: [10_000 + i],
          buffered_txn_count: 0,
          buffered_txns: []
        }
      end

    Map.put(state, :active_moves, active_moves)
  end

  defp ets_info_bytes(table) do
    case :ets.info(table, :memory) do
      words when is_integer(words) -> words * @wordsize
      _ -> 0
    end
  end

  def ets_bytes(filter) do
    ets_info_bytes(filter.subquery_index.table) +
      ets_info_bytes(filter.subquery_index.counters)
  end

  def mtv_bytes(filter) do
    ets_info_bytes(filter.subquery_index.multi_time_view)
  end

  def consumer_bytes(state) do
    consumer_size =
      state.consumer_states
      |> Enum.map(&(:erts_debug.size(&1) * @wordsize))
      |> Enum.sum()

    move_size =
      Map.get(state, :active_moves, [])
      |> Enum.map(&(:erts_debug.size(&1) * @wordsize))
      |> Enum.sum()

    consumer_size + move_size
  end

  def measure(label, state) do
    ets = ets_bytes(state.filter) + mtv_bytes(state.filter)
    consumers = consumer_bytes(state)
    total = ets + consumers

    %{
      label: label,
      ets: ets,
      consumers: consumers,
      total: total
    }
  end

  def human(bytes) when bytes < 1024, do: "#{bytes} B"

  def human(bytes) when bytes < 1024 * 1024,
    do: :erlang.float_to_binary(bytes / 1024, decimals: 1) <> " KiB"

  def human(bytes), do: :erlang.float_to_binary(bytes / 1_048_576, decimals: 2) <> " MiB"

  def print_table(rows) do
    IO.puts("")

    IO.puts(
      "| Scenario | Logical total | Logical ETS | Logical consumers |"
    )

    IO.puts(
      "|----------|---------------|-------------|-------------------|"
    )

    for r <- rows do
      IO.puts(
        "| #{r.label} | #{human(r.total)} | #{human(r.ets)} | #{human(r.consumers)} |"
      )
    end

    IO.puts("")
  end
end

# ============================================================================
# Scenarios
# ============================================================================

scenarios = [
  fn ->
    MemBench.build_steady(1, 1_000)
    |> then(&MemBench.measure("1 shape, 1k values, steady", &1))
  end,
  fn ->
    MemBench.build_steady(10, 1_000)
    |> then(&MemBench.measure("10 shapes, 1k values, steady", &1))
  end,
  fn ->
    MemBench.build_steady(100, 1_000)
    |> then(&MemBench.measure("100 shapes, 1k values, steady", &1))
  end,
  fn ->
    MemBench.build_steady(100, 10_000)
    |> then(&MemBench.measure("100 shapes, 10k values, steady", &1))
  end,
  fn ->
    MemBench.build_steady(100, 1_000)
    |> MemBench.apply_advanced(100, 10)
    |> then(&MemBench.measure("100 shapes, 1k base, 100 added x 10 advanced", &1))
  end,
  fn ->
    MemBench.build_steady(100, 1_000)
    |> MemBench.apply_advanced(100, 99)
    |> then(&MemBench.measure("100 shapes, 1k base, 100 added x 99 advanced", &1))
  end,
  fn ->
    MemBench.build_steady(100, 1_000)
    |> MemBench.apply_advanced(100, 10)
    |> MemBench.apply_active_moves(10, 100)
    |> then(&MemBench.measure("100 shapes, 1k base, 100 added x 10 active move", &1))
  end,
  fn ->
    MemBench.build_steady(100, 1_000)
    |> MemBench.apply_advanced(1_000, 99)
    |> MemBench.apply_active_moves(99, 1_000)
    |> then(&MemBench.measure("100 shapes, 1k base, 1k added x 99 active move", &1))
  end
]

results =
  for scenario <- scenarios do
    # Each scenario builds its own private ETS; force a GC between to keep
    # the numbers comparable.
    :erlang.garbage_collect()
    result = scenario.()
    :erlang.garbage_collect()
    result
  end

IO.puts("# SubqueryIndex memory snapshot")
IO.puts("")

IO.puts(
  "OTP: #{:erlang.system_info(:otp_release)}  Wordsize: #{:erlang.system_info(:wordsize)} bytes"
)

IO.puts("Elixir: #{System.version()}")

MemBench.print_table(results)
