LUX_BIN="$SCRIPT_DIR/lux/bin/lux"

lux:
	git clone https://github.com/hawk/lux.git && \
	cd lux && \
	git checkout 629e45c59a352ec49e0b51dde95d4247b579bfa9 && \
	autoconf && \
	./configure && \
	make
