/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    electricRegionVpc2EuWest1: {
      type: "sst.aws.Vpc"
    }
    phoenixLiveviewServiceEuWest1: {
      service: string
      type: "sst.aws.Service"
      url: string
    }
  }
}
