/*
  Autogenerated ElectricSQL config file. Don't edit this
  file directly. Instead, use the `electric` CLI tool
  to manage your config and migrations.

  See https://electric-sql.com/docs for more information.
*/

export default {
  "app": "linearlite",
  "build": "local",
  "console": {
    "host": "127.0.0.1",
    "port": 4000,
    "ssl": false
  },
  "debug": false,
  "env": "local",
  "replication": {
    "host": "127.0.0.1",
    "port": 5133,
    "ssl": false
  }
}
