start:
	docker compose up

start_without_electric:
	docker compose up postgres_1

start_electric:
	docker compose up electric_1

stop:
	docker compose down --volumes

clean:
	docker volume rm -f local-stack_pg_data

