stop:
	docker compose down --volumes

clean:
	docker volume rm -f local-stack_electric_data
	docker volume rm -f local-stack_pg_data
	docker volume rm -f local-stack_vaxine_data
	docker volume rm -f local-stack_migrations_volume

