name: Deploy Linearlite Production

on:
    push:
      branches: ['main']
      paths: ['examples/linearlite/**']
    pull_request:
      paths: ['examples/linearlite/**']

jobs:
  deploy-linearlite:
    name: Deploy Linearlite Production
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache SST state
        uses: actions/cache@v4
        with:
          path: .sst
          key: sst-cache-main-${{ runner.os }}
          restore-keys: |
            sst-cache-main-${{ runner.os }}

      - name: Initialize SST environment
        run: |
          sudo apt install -y tini

      - name: Deploy to production stack
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_DEFAULT_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_DEFAULT_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
          ELECTRIC_API: ${{ secrets.ELECTRIC_API }}
          ELECTRIC_ADMIN_API: ${{ secrets.ELECTRIC_ADMIN_API }}
          # HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }} TODO
        run: |
          exec tini -s -g -- pnpm sst deploy --stage production