name: Electric Docker Image Smoke Test

on:
  pull_request:
    paths:
      - "packages/sync-service/**"
    paths-ignore:
      - "**/README.md"

permissions:
  packages: write

jobs:
  docker_image_smoketest:
    name: Docker image smoke test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/sync-service
    services:
      postgres:
        image: "postgres:17-alpine"
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 54321:5432
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: packages/sync-service
          push: true
          tags: "ghcr.io/electric-sql/electric/electric:smoketest"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: |
          docker run \
            --rm \
            -t \
            -e ELECTRIC_USAGE_REPORTING=false \
            -e ELECTRIC_INSECURE=true \
            -e DATABASE_URL='postgresql://postgres:password@localhost:54321' \
            -p 3000:3000 \
            ghcr.io/electric-sql/electric/electric:smoketest
