name: Publish Electric images to Docker Hub

# If you decide to modify the list of triggers for this action, don't forget to also update the
# conditional logic in the derive_build_vars job below.
on:
  push:
    branches: ['main']
  release:
    types: [released]
  # Allows the workflow to be called by the Changesets workflow
  workflow_call:
    inputs:
      release_tag:
        description: 'The @core/sync-service@... tag passed from caller'
        required: true
        type: string
  # Allows the workflow to be triggered manually from the UI
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The @core/sync-service@... tag to run the workflow for (e.g. @core/sync-service@1.2.10)'
        required: true
        type: string

env:
  DOCKERHUB_REPO: electricsql/electric
  DOCKERHUB_CANARY_REPO: electricsql/electric-canary

jobs:
  derive_build_vars:
    name: Derive build variables from the source code
    runs-on: blacksmith-2vcpu-ubuntu-2404
    outputs:
      git_ref: ${{ steps.git_ref.outputs.git_ref }}
      is_release: ${{ steps.git_ref.outputs.is_release }}
      short_commit_sha: ${{ steps.vars.outputs.short_commit_sha }}
      electric_version: ${{ steps.vars.outputs.electric_version }}

    steps:
      - name: Determine the ref to check out
        id: git_ref
        env:
          INPUT_RELEASE_TAG: ${{ inputs.release_tag }}
          EVENT_RELEASE_TAG: ${{ github.event.release.tag_name }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          if [ -n "$INPUT_RELEASE_TAG" ]; then
            ref="refs/tags/$INPUT_RELEASE_TAG"
            is_release=true
          elif [ -n "$EVENT_RELEASE_TAG" ]; then
            ref="refs/tags/$EVENT_RELEASE_TAG"
            is_release=true
          else
            ref="$COMMIT_SHA"
            is_release=false
          fi

          echo "git_ref=$ref" >> $GITHUB_OUTPUT
          echo "is_release=$is_release" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          # The checked out commit influences the value of the ELECTRIC_VERSION variable
          # that is baked into the Docker image.
          #
          # For regular pushes to main, we check out the HEAD commit and publish canary images.
          #
          # For releases we check out the tag corresponding to the release, e.g.
          # @core/sync-service@v1.2.10.
          #
          # For manual triggers via workflow_dispatch, we check out the tag specified manually
          # by the actor.
          ref: ${{ steps.git_ref.outputs.git_ref }}
          # Also important to fetch the whole history since otherwise we won't get that tags
          # that are required to determine the correct ELECTRIC_VERSION.
          fetch-depth: 0
          fetch-tags: true

      - name: Determine short_commit_sha and electric_version to use in the build step
        id: vars
        run: |
          echo "short_commit_sha=$(
            git rev-parse --short HEAD
          )" >> $GITHUB_OUTPUT

          echo "electric_version=$(
            git describe --abbrev=7 --tags --always --first-parent --match '@core/sync-service@*' | sed -En 's|^@core/sync-service@||p'
          )" >> $GITHUB_OUTPUT

  derive_tags:
    name: Derive Docker image tags
    needs: [derive_build_vars]
    runs-on: blacksmith-2vcpu-ubuntu-2404
    outputs:
      electric_tags: ${{ steps.tags.outputs.electric_tags }}
      canary_tags: ${{ steps.tags.outputs.canary_tags }}
    steps:
      - name: Derive image tags from the GitHub Actions event
        id: tags
        run: |
          if [ "${{ needs.derive_build_vars.outputs.is_release }}" = "true" ]; then
            # A release triggers official release image publishing
            echo "electric_tags=-t $DOCKERHUB_REPO:latest -t $DOCKERHUB_REPO:${{ needs.derive_build_vars.outputs.electric_version }}" >> $GITHUB_OUTPUT
            echo "canary_tags=" >> $GITHUB_OUTPUT
          else
            # A regular push to the main branch triggers canary image publishing
            echo "electric_tags=-t $DOCKERHUB_REPO:canary" >> $GITHUB_OUTPUT
            echo "canary_tags=-t $DOCKERHUB_CANARY_REPO:latest -t $DOCKERHUB_CANARY_REPO:${{ needs.derive_build_vars.outputs.short_commit_sha }}" >> $GITHUB_OUTPUT
          fi

  build_and_publish:
    needs: [derive_build_vars, derive_tags]
    uses: ./.github/workflows/_build_and_publish_electric_image.yml
    secrets: inherit
    with:
      git_ref: ${{ needs.derive_build_vars.outputs.git_ref }}
      electric_version: ${{ needs.derive_build_vars.outputs.electric_version }}
      electric_tags: ${{ needs.derive_tags.outputs.electric_tags }}
      canary_tags: ${{ needs.derive_tags.outputs.canary_tags }}
