name: Test Examples

on:
  workflow_call:
  schedule:
    - cron: '0 9 * * *' # Runs daily at 9 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  example-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-example-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Create example matrix
        id: create-example-matrix
        run: node scripts/ci/example-matrix.mjs productionTest

  test:
    name: Test ${{ matrix.example.name }} example
    needs: example-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.example-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Test ${{ matrix.example.name }} example
        uses: ./.github/actions/test-example
        with:
          test_folder: ${{ matrix.example.test_folder }}
          example_url: ${{ matrix.example.production_url }}
